- name: Install Docker
  package:
    state: latest
    name:
      - docker.io
      - docker-compose

- name: Ensure ansible_user is added to the docker group.
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable docker.service
  systemd:
    name: docker.service
    daemon_reload: true
    enabled: true

- name: Test if docker is working
  docker_container:
    name: testing
    image: busybox
    state: started
    detach: false
    cleanup: true
