- name: Install htpdate package
  package:
    state: latest
    name:
      - htpdate

- name: Timezone SP
  timezone:
    name: "{{ timezone }}"

- name: Sync time with htpdate
  command: htpdate -s time.google.com
