- name: Set default as DNS operational mode
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: default
    no_extra_spaces: yes
  notify:
    - "Remove STUB"
    - "Restart NM"
- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
    masked: yes
  notify:
    - "Remove STUB"
    - "Restart NM"
